services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: copilot_db
      POSTGRES_USER: copilot_user
      POSTGRES_PASSWORD: copilot_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    driver: local

