CREATE TABLE IF NOT EXISTS customer (
    id UUID PRIMARY KEY DEFAULT RANDOM_UUID(),
    full_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    national_id VARCHAR(50) NOT NULL,
    phone_number VARCHAR(50) NOT NULL,
    status VARCHAR(20) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);